import type { Metadata } from 'next';
import { Prata, Poppins } from 'next/font/google';
import './globals.css';

const prata = Prata({
  variable: '--font-prata',
  subsets: ['latin'],
  weight: '400',
});

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${prata.variable} ${poppins.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
